### ISSUE TITLE
Storing to synapse from distributed jobs creates a race condition

### ISSUE THREAD

**Issue by pvtodorov** [pvtodorov/btr#21]
- it is possible that a parent project/folder/etc on synapse has been edited or updated since the last time the local client accessed it. This creates a race condition and the upload fails

```Traceback (most recent call last):
  File "/home/as773/amp-ad/lib/python3.6/site-packages/synapseclient/client.py", line 1051, in store
    properties = self._createEntity(properties)
  File "/home/as773/amp-ad/lib/python3.6/site-packages/synapseclient/client.py", line 3421, in _createEntity
    return self.restPOST(uri='/entity', body=json.dumps(get_properties(entity)))
  File "/home/as773/amp-ad/lib/python3.6/site-packages/synapseclient/client.py", line 3563, in restPOST
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/home/as773/amp-ad/lib/python3.6/site-packages/synapseclient/exceptions.py", line 140, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.exceptions.SynapseHTTPError: 409 Client Error: Conflict
An entity with the name: Runs already exists with a parentId: syn11615746

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/as773/amp-ad/bin/btr-predict", line 11, in <module>
    load_entry_point('btr', 'console_scripts', 'btr-predict')()
  File "/home/as773/amp-ad/btr/btr/predict.py", line 26, in main
    loader.save_prediction_to_synapse()
  File "/home/as773/amp-ad/btr/btr/loader.py", line 59, in save_prediction_to_synapse```

**Comment by pvtodorov** [comment]
closed by #22
